version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: micro_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - spring-network

  journal-service:
    build:
      context: ./journal-service
    container_name: journal-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
